//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAdresses
    {
        public int AccountAdressesId { get; set; }
        public int AccountId { get; set; }
        public string PhoneNumber { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public short IsMainAdress { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
