//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ccontact
    {
        public int ConcactId { get; set; }
        public string Message { get; set; }
        public string Topic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }
}
