//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Developer()
        {
            this.ProjectDeveloper = new HashSet<ProjectDeveloper>();
            this.StageTeam = new HashSet<StageTeam>();
            this.TechnologiesDeveloper = new HashSet<TechnologiesDeveloper>();
        }
    
        public int DeveloperId { get; set; }
        public int AccountId { get; set; }
        public string ExperienceFromDate { get; set; }
        public string CostPerHour { get; set; }
        public string WeekAvailability { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDeveloper> ProjectDeveloper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageTeam> StageTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnologiesDeveloper> TechnologiesDeveloper { get; set; }
    }
}
