//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HarrierEntities : DbContext
    {
        public HarrierEntities()
            : base("name=HarrierEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountAdresses> AccountAdresses { get; set; }
        public virtual DbSet<Ccontact> Ccontact { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Developer> Developer { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectData> ProjectData { get; set; }
        public virtual DbSet<ProjectDeveloper> ProjectDeveloper { get; set; }
        public virtual DbSet<ProjectStage> ProjectStage { get; set; }
        public virtual DbSet<ProjectTechnologies> ProjectTechnologies { get; set; }
        public virtual DbSet<Stages> Stages { get; set; }
        public virtual DbSet<StageTeam> StageTeam { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Technologies> Technologies { get; set; }
        public virtual DbSet<TechnologiesDeveloper> TechnologiesDeveloper { get; set; }
    }
}
