//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStage
    {
        public int ProjectStageId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string DeathLine { get; set; }
        public string StageNumber { get; set; }
        public int Project_id { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
