//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDeveloper
    {
        public int ProjectDeveloperId { get; set; }
        public int DeveloperId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Project Project { get; set; }
    }
}
