//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectData = new HashSet<ProjectData>();
            this.ProjectDeveloper = new HashSet<ProjectDeveloper>();
            this.ProjectStage = new HashSet<ProjectStage>();
            this.ProjectTechnologies = new HashSet<ProjectTechnologies>();
            this.Stages = new HashSet<Stages>();
        }
    
        public int ProjectId { get; set; }
        public int AccountId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DeathLine { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EstimatedHours { get; set; }
        public Nullable<int> LoggedHours { get; set; }
        public Nullable<int> StartedByAccount { get; set; }
        public int ProjectStatus { get; set; }
        public int ProjectLeaderId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectData> ProjectData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDeveloper> ProjectDeveloper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStage> ProjectStage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTechnologies> ProjectTechnologies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stages> Stages { get; set; }
    }
}
