//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageTeam
    {
        public int StageTeamId { get; set; }
        public int StagesID { get; set; }
        public Nullable<short> IsStageLeader { get; set; }
        public int Developer_idDeveloper { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Stages Stages { get; set; }
    }
}
