//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stages()
        {
            this.StageTeam = new HashSet<StageTeam>();
        }
    
        public int StageId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> StageNumber { get; set; }
        public Nullable<System.DateTime> StageStartDate { get; set; }
        public Nullable<System.DateTime> StageEndDate { get; set; }
        public Nullable<short> StageAccepted { get; set; }
        public Nullable<int> StageLeaderDeveloperId { get; set; }
        public string StageDescription { get; set; }
        public Nullable<int> StageStatus { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StageTeam> StageTeam { get; set; }
    }
}
