//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Harrier.WebUI.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnologiesDeveloper
    {
        public int TechnologiesDeveloperId { get; set; }
        public int TechnologiesId { get; set; }
        public int DeveloperId { get; set; }
        public Nullable<System.DateTime> experience_from { get; set; }
        public Nullable<int> skill_level { get; set; }
        public Nullable<short> is_tech_promotor { get; set; }
        public Nullable<short> technology_promotor_approved { get; set; }
    
        public virtual Developer Developer { get; set; }
        public virtual Technologies Technologies { get; set; }
    }
}
